[metadata]
name = gripper_control
version = 0.0.0

[options]
packages = find:
install_requires =
    setuptools
zip_safe = false

[options.entry_points]
console_scripts =
    lite6_gripper_ws = gripper_control.lite6_gripper_ws:main

[develop]
script_dir=$base/lib/gripper_control

[install]
install_scripts=$base/lib/gripper_control
